Repository juntossomosmais/atomium, pull requests merged in 2023-12, with the labels that each got.

#329 chore(deps): update dependencies
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: dependencies

#330 fix(core): remove lifecycle methods from inputs
  packages/core/src/components/input/input.tsx
  packages/core/src/components/select/select.spec.ts
  packages/core/src/components/select/select.tsx
  packages/core/src/components/textarea/textarea.spec.ts
  packages/core/src/components/textarea/textarea.tsx
Labels: improvements

#348 fix: adjust white color in fill clear
  packages/core/src/components/button/button.scss
Labels: improvements

#350 fix(core): add more specific has-icon class
  packages/core/src/components/input/input.scss
Labels: layout, improvements

#351 feat(icons): add new icons for select
  package-lock.json
  packages/core/src/components.d.ts
  packages/core/src/icons.d.ts
  packages/icons/svg/mdi/calendar-today-outline.svg
  packages/icons/svg/mdi/calendar-today.svg
  packages/icons/svg/mdi/store-outline.svg
  packages/icons/svg/mdi/store.svg
  packages/icons/svg/mdi/tune.svg
Labels: package/icons

#356 feat: new prop to center corousel component
  packages/core/src/components.d.ts
  packages/core/src/components/carousel/carousel.spec.ts
  packages/core/src/components/carousel/carousel.tsx
  packages/core/src/components/carousel/stories/carousel.args.ts
Labels: improvements

#358 feat(icons): add compare arrows icon
  packages/core/src/icons.d.ts
  packages/icons/svg/mdi/compare-arrows.svg
Labels: package/icons
