Repository juntossomosmais/atomium, pull requests merged in 2023-09, with the labels that each got.

#257 chore(deps): update @juntossomosmais/linters
  .stylelintrc.json
  package-lock.json
  package.json
Labels: dependencies

#258 docs(readme): adding infos how to configure ssh token
  .npmrc.example
  README.md
Labels: documentation

#259 chore: normalize files using prettier
  .stylelintrc.json
  apps/docs-react/.prettierrc.js
  apps/docs-react/.storybook/manager-head.html
  apps/docs-react/babel.config.json
  apps/docs-react/stories/0_Introduction.stories.mdx
  apps/docs/.prettierrc.js
  apps/docs/.storybook/manager-head.html
  apps/docs/stories/0_Introduction.stories.mdx
  apps/docs/stories/1_0_Core.stories.mdx
  apps/docs/stories/1_1_React.stories.mdx
  apps/docs/stories/1_2_Vue.stories.mdx
  apps/docs/stories/1_3_Tokens.stories.mdx
  apps/docs/stories/1_4_Icons.stories.mdx
  apps/docs/stories/architecture-decision-records/0000-why-design-system.stories.mdx
  apps/docs/stories/architecture-decision-records/0001-why-web-components.stories.mdx
  apps/docs/stories/architecture-decision-records/0002-why-ionic.stories.mdx
  apps/docs/stories/architecture-decision-records/0003-why-stencil.stories.mdx
  apps/docs/stories/architecture-decision-records/0004-why-a-monorepo.stories.mdx
  apps/docs/stories/architecture-decision-records/0005-why-nx.stories.mdx
  apps/docs/stories/architecture-decision-records/0006-why-that-component-creation-definition.stories.mdx
  apps/docs/stories/architecture-decision-records/0007-why-do-we-transpile-web-components-for-react-and-not-for-vue.stories.mdx
  apps/docs/stories/architecture-decision-records/0008-why-do-we-need-grids.stories.mdx
  apps/docs/stories/architecture-decision-records/0009-why-use-onclick-event-on-breadcrumb-component-event-undocumented.stories.mdx
  apps/docs/stories/architecture-decision-records/0010-why-do-we-need-react-fix.stories.mdx
  apps/docs/stories/architecture-decision-records/0011-why-host-our-own-icon-library-and-cdn.stories.mdx
  apps/docs/stories/architecture-decision-records/0012-why-have-a-carousel-with-swiper.stories.mdx
  apps/docs/stories/architecture-decision-records/0013-why-using-virtual-carousel-item.stories.mdx
  package-lock.json
  package.json
  packages/core/postcss.config.js
  packages/core/src/components/alert/alert.tsx
  packages/core/src/components/badge/badge.tsx
  packages/core/src/components/breadcrumb/breadcrumb.tsx
  packages/core/src/components/button/button.tsx
  packages/core/src/components/button/stories/button.react.stories.tsx
  packages/core/src/components/carousel/carousel.tsx
  packages/core/src/components/carousel/stories/carousel-item/carousel-item.react.stories.tsx
  packages/core/src/components/carousel/stories/carousel/carousel.core.stories.tsx
  packages/core/src/components/carousel/stories/carousel/carousel.react.stories.tsx
  packages/core/src/components/chip/chip.tsx
  packages/core/src/components/grid/grid.tsx
  packages/core/src/components/grid/stories/grid.react.stories.tsx
  packages/core/src/components/icon/icon.tsx
  packages/core/src/components/input/input.scss
  packages/core/src/components/input/input.tsx
  packages/core/src/components/input/stories/input.react.stories.tsx
  packages/core/src/components/select/select.scss
  packages/core/src/components/select/select.tsx
  packages/core/src/components/textarea/stories/textarea.react.stories.tsx
  packages/core/src/components/textarea/textarea.scss
  packages/tokens/rollup.config.mjs
  packages/tokens/src/index.scss
  packages/tokens/stories/1_Colors.stories.mdx
  packages/tokens/stories/2_Spacings.stories.mdx
  packages/tokens/stories/3_Typography.stories.mdx
  packages/tokens/stories/4_Screens.stories.mdx
  packages/tokens/stories/5_Grid.stories.mdx
  packages/tokens/stories/6_Misc.stories.mdx
  packages/tokens/stories/7_Elevation.stories.mdx
  utils/storybook/preview.css
Labels: improvements

#267 fix(carousel): add touch-start-prevent-default as default prop
  packages/core/src/components/carousel/carousel.spec.ts
  packages/core/src/components/carousel/carousel.tsx
Labels: package/core, components, improvements

#261 feat: add tag component
  packages/core/src/components/tag/stories/tag.args.ts
  packages/core/src/components/tag/stories/tag.core.stories.tsx
  packages/core/src/components/tag/stories/tag.react.stories.tsx
  packages/core/src/components/tag/tag.scss
  packages/core/src/components/tag/tag.spec.ts
  packages/core/src/components/tag/tag.tsx
  packages/tokens/src/tokens.scss
  packages/tokens/stories/3_Typography.stories.mdx
Labels: components

#269 chore: extends eslint from @juntossomosmais/linters
  .eslintignore
  .eslintrc.js
  .eslintrc.json
  apps/docs-react/.eslintrc.json
  apps/docs/.eslintrc.json
  package-lock.json
  package.json
  packages/core/.eslintrc.json
  packages/react/.eslintrc.json
  packages/tokens/.eslintrc.json
  packages/vue/.eslintrc.json
Labels: improvements
