Repository juntossomosmais/atomium, pull requests merged in 2024-08, with the labels that each got.

#520 chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#521 feat(icons): add icon of pix
  packages/core/src/icons.d.ts
  packages/icons/svg/custom/pix.svg
Labels: package/icons

#526 chore: improve template pr with suggestion title and add rule
  .github/pull_request_template.md
  .github/workflows/pr-title-check.yml
Labels: documentation

#525 feat(icons): add icon of pix colerful
  apps/docs/stories/1_4_Icons.stories.mdx
  packages/core/src/icons.d.ts
  packages/icons/svg/custom/pix-colorful.svg
Labels: package/icons

#532 chore(gh-actions): fix regex pr title rule
  .github/workflows/pr-title-check.yml
Labels: ci

#531 fix(button): decrease horizontal padding size
  packages/core/src/components/button/button.scss
Labels: layout, improvements

#534 feat(modal): add modal component
  apps/docs-react/.storybook/preview.ts
  apps/docs-vue/.storybook/preview.ts
  apps/docs/.storybook/preview.ts
  packages/core/src/components.d.ts
  packages/core/src/components/button/button.spec.ts
  packages/core/src/components/button/button.tsx
  packages/core/src/components/modal/modal.scss
  packages/core/src/components/modal/modal.spec.ts
  packages/core/src/components/modal/modal.tsx
  packages/core/src/components/modal/stories/modal.args.ts
  packages/core/src/components/modal/stories/modal.core.stories.tsx
  packages/core/src/components/modal/stories/modal.react.stories.tsx
  packages/core/src/components/modal/stories/modal.vue.stories.tsx
  utils/storybook/templates/DocumentationTemplate.mdx
  utils/storybook/templates/DocumentationWithoutStories.mdx
Labels: components

#539 feat(icons): add verified icons
  packages/core/src/icons.d.ts
  packages/icons/svg/mdi/verified-outiline.svg
  packages/icons/svg/mdi/verified.svg
Labels: package/icons

#540 fix(icons): rename verified outline icon
  packages/core/src/icons.d.ts
  packages/icons/svg/mdi/verified-outiline.svg
  packages/icons/svg/mdi/verified-outline.svg
Labels: bug

#542 fix(tag): light tag color
  packages/core/src/components/tag/tag.scss
  packages/core/src/components/tag/tag.spec.ts
  packages/core/src/components/tag/tag.tsx
Labels: bug, layout

#543 fix(alert): improve position of icon on single line
  packages/core/src/components/alert/alert.scss
Labels: components, improvements

#545 feat(link): set default color and add size prop
  packages/core/src/components.d.ts
  packages/core/src/components/link/link.scss
  packages/core/src/components/link/link.spec.ts
  packages/core/src/components/link/link.tsx
  packages/core/src/components/link/stories/link.args.ts
  packages/core/src/components/link/stories/link.core.stories.tsx
Labels: layout, improvements

#547 feat(icon): add white color
  packages/core/src/components.d.ts
  packages/core/src/components/icon/icon.scss
  packages/core/src/components/icon/icon.tsx
  packages/core/src/components/icon/stories/icon.args.ts
Labels: package/core, components
