Repository juntossomosmais/atomium, pull requests merged in 2025-05, with the labels that each got.

#726 feat(component): create stepper component
  packages/core/src/components.d.ts
  packages/core/src/components/stepper/stepper.scss
  packages/core/src/components/stepper/stepper.spec.ts
  packages/core/src/components/stepper/stepper.tsx
  packages/core/src/components/stepper/stories/stepper.args.ts
  packages/core/src/components/stepper/stories/stepper.core.stories.tsx
  packages/core/src/components/stepper/stories/stepper.react.stories.tsx
  packages/core/src/components/stepper/stories/stepper.vue.stories.tsx
  packages/core/src/utils/screens.ts
Labels: components

#754 feat(datetime): add date-target and time-target slots
  packages/core/src/components/datetime/datetime.spec.ts
  packages/core/src/components/datetime/datetime.tsx
  packages/core/src/components/datetime/stories/datetime.args.ts
  packages/core/src/components/datetime/stories/datetime.core.stories.tsx
  packages/core/src/components/datetime/stories/datetime.react.stories.tsx
  packages/core/src/components/datetime/stories/datetime.vue.stories.tsx
Labels: improvements

#755 fix(deps): downgrade stencil version
  package-lock.json
  package.json
  packages/core/loader/package.json
  packages/core/package.json
Labels: bug, dependencies
