Repository juntossomosmais/atomium, pull requests merged in 2025-03, with the labels that each got.

#715 chore(deps): update dev dependencies
  package-lock.json
  package.json
  packages/core/src/icons.d.ts
Labels: dependencies

#716 fix(modal): show buttons modal only buttons have text
  packages/core/src/components.d.ts
  packages/core/src/components/modal/modal.spec.ts
  packages/core/src/components/modal/modal.tsx
Labels: components, improvements

#727 ci(gh-actions): add cdn deployment workflow
  .github/workflows/deploy-to-cdn.yml
  .github/workflows/icons.yml
  README.md
  apps/docs/stories/architecture-decision-records/0015-why-use-cdn-for-distribution.mdx
  packages/core/README.md
Labels: documentation, ci

#728 feat(modal): add overflow in modal
  packages/core/src/components/modal/modal.scss
Labels: improvements

#731 feat(modal): add metadata prop allowing automated tests
  package-lock.json
  packages/core/src/components.d.ts
  packages/core/src/components/modal/modal.spec.ts
  packages/core/src/components/modal/modal.tsx
  packages/core/src/components/modal/stories/modal.args.ts
  packages/core/src/components/modal/stories/modal.core.stories.tsx
  packages/core/src/components/modal/stories/modal.react.stories.tsx
  packages/core/src/components/modal/stories/modal.vue.stories.tsx
Labels: documentation, improvements
