Repository juntossomosmais/atomium, pull requests merged in 2025-04, with the labels that each got.

#736 chore(deps): update rupture for compatibility with modern scss
  package-lock.json
  package.json
  utils/scss/rupture.scss
  utils/scss/screens.scss
Labels: dependencies

#738 chore(deps): update scss configs to use with new version
  .stylelintrc.json
  package-lock.json
  package.json
  packages/core/src/components/alert/alert.scss
  packages/core/src/components/breadcrumb/breadcrumb.scss
  packages/core/src/components/meter/meter.scss
  packages/core/src/components/modal/modal.scss
  packages/tokens/src/index.scss
  packages/tokens/src/tokens.scss
  utils/scss/index.scss
  utils/scss/rupture.scss
  utils/scss/screens.scss
Labels: dependencies

#737 chore(deps): bump dev dependencies
  package-lock.json
  package.json
Labels: dependencies

#741 feat: add meta data on steps modal
  package-lock.json
  package.json
  packages/core/src/components.d.ts
  packages/core/src/components/modal/stories/modal.args.ts
  packages/core/src/components/steps-modal/steps-modal.spec.ts
  packages/core/src/components/steps-modal/steps-modal.tsx
  packages/core/src/components/steps-modal/stories/steps-modal.args.ts
  packages/core/src/components/steps-modal/stories/steps-modal.core.stories.tsx
  packages/core/src/components/steps-modal/stories/steps-modal.react.stories.tsx
  packages/core/src/components/steps-modal/stories/steps-modal.vue.stories.tsx
Labels: components, improvements

#746 feat(tooltip): custom bg variable
  .github/workflows/preview.yml
  packages/core/src/components/tooltip/stories/tooltip.args.ts
  packages/core/src/components/tooltip/tooltip.scss
Labels: improvements

#749 fix(alert): add dompurify to resolve injection problems
  package-lock.json
  package.json
  packages/core/src/components/alert/alert.tsx
Labels: bug, components
